import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// These sidebar files are auto-generated by `npm run gen-api-docs`.
// Run `npm run regen` after updating openapi/*.yaml to regenerate them.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const publicApiSidebar = require('./docs/api/public/sidebar');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const privateApiSidebar = require('./docs/api/private/sidebar');

const sidebars: SidebarsConfig = {

  gettingStartedSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: '🚀 Installation',
      collapsed: false,
      items: [
        'installation/index',
        'installation/system-requirements',
        'installation/softaculous',
        'installation/cpanel-shared-hosting',
        'installation/self-hosted',
        'installation/ubuntu',
        'installation/rocky-linux',
        'installation/azure',
        'installation/vps-cloud',
        'installation/ssl-https',
      ],
    },
    {
      type: 'category',
      label: '⚙️ First Run',
      collapsed: false,
      items: [
        'getting-started/first-run',
        'getting-started/first-week',
        'getting-started/features-overview',
      ],
    },
  ],

  userGuideSidebar: [
    {
      type: 'doc',
      id: 'user-guide/index',
      label: 'User Guide Overview',
    },
    {
      type: 'category',
      label: '👥 People & Families',
      items: [
        'user-guide/persons',
        'user-guide/families',
        'user-guide/classifications',
        'user-guide/custom-fields',
        'user-guide/custom-fields-types',
        'user-guide/properties',
        'user-guide/notes',
        'user-guide/search',
      ],
    },
    {
      type: 'category',
      label: '📅 Groups & Events',
      items: [
        'user-guide/groups',
        'user-guide/events',
        'user-guide/sunday-school',
        'user-guide/volunteers',
        {
          type: 'category',
          label: 'Volunteer Management (v2)',
          link: { type: 'doc', id: 'user-guide/ministries/index' },
          items: [
            'user-guide/ministries/ministries-teams-positions',
            'user-guide/ministries/volunteers-and-qualifications',
            'user-guide/ministries/events-and-calendar',
            'user-guide/ministries/schedules-and-occurrences',
            'user-guide/ministries/staffing-an-occurrence',
            'user-guide/ministries/substitutions',
            'user-guide/ministries/ministry-dashboard',
            'user-guide/ministries/email-and-reminders',
            'user-guide/ministries/permissions',
          ],
        },
        'user-guide/kiosk-devices',
      ],
    },
    {
      type: 'category',
      label: '💰 Finance',
      items: [
        'user-guide/finances',
        'user-guide/deposit-search',
        'user-guide/pledge-dashboard',
        'user-guide/fund-contributors',
        'user-guide/cart',
        'user-guide/fundraiser',
      ],
    },
    {
      type: 'category',
      label: '📧 Communications',
      items: [
        'user-guide/email',
        'user-guide/reports-and-queries',
        'user-guide/geographic',
        'user-guide/data-import',
        'user-guide/export',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: '🔓 Public API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/public/index',
          label: 'Overview',
        },
        ...publicApiSidebar,
      ],
    },
    {
      type: 'category',
      label: '🔒 Private API',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'api/private/index',
          label: 'Overview',
        },
        ...privateApiSidebar,
      ],
    },
  ],

  adminSidebar: [
    {
      type: 'doc',
      id: 'administration/index',
      label: 'Administration Overview',
    },
    {
      type: 'category',
      label: '🔧 System Management',
      items: [
        'administration/users',
        'administration/security',
        'administration/secret-keys',
        'administration/email-setup',
        'administration/localization',
        'administration/reset-password',
        'administration/notifications',
        'administration/api-tokens',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Configuration',
      items: [
        'administration/system-settings',
        'administration/maps-and-geocoding',
        'administration/server-locale',
      ],
    },
    {
      type: 'category',
      label: '🔄 Maintenance',
      items: [
        'administration/upgrade',
        'administration/backup-restore',
        'administration/rollback',
        'administration/file-system-permissions',
      ],
    },
    {
      type: 'category',
      label: '🩺 Troubleshooting',
      items: [
        'administration/troubleshooting',
        'administration/faqs',
        'administration/logging-and-diagnostics',
        'administration/bug-reporting-and-diagnostics',
        'administration/reporting-issues',
      ],
    },
    {
      type: 'category',
      label: '🔌 Plugins',
      items: [
        'administration/plugins/index',
        'administration/plugins/installing-community-plugins',
        'administration/plugins/plugin-security-and-compliance',
        'administration/plugins/plugin-localization',
      ],
    },
  ],

};

export default sidebars;
